micronaut:
  application:
    name: todo-list
  datasources:
    default:
      url: jdbc:postgresql://db:5432/postgres
      driverClassName: org.postgresql.Driver
      username: postgres
      password: postgres
      dialect: org.hibernate.dialect.PostgreSQLDialect